# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Jon\OneDrive\dev\monster_maker\monster_forge\gui\\view\qt_designer\trait_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TraitView(object):
    def setupUi(self, TraitView):
        TraitView.setObjectName("TraitView")
        TraitView.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(TraitView)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_trait = QtWidgets.QLabel(TraitView)
        self.lbl_trait.setText("")
        self.lbl_trait.setObjectName("lbl_trait")
        self.horizontalLayout.addWidget(self.lbl_trait)
        self.btn_edit_trait = QtWidgets.QPushButton(TraitView)
        self.btn_edit_trait.setObjectName("btn_edit_trait")
        self.horizontalLayout.addWidget(self.btn_edit_trait)
        self.btn_delete_trait = QtWidgets.QPushButton(TraitView)
        self.btn_delete_trait.setObjectName("btn_delete_trait")
        self.horizontalLayout.addWidget(self.btn_delete_trait)

        self.retranslateUi(TraitView)
        QtCore.QMetaObject.connectSlotsByName(TraitView)

    def retranslateUi(self, TraitView):
        _translate = QtCore.QCoreApplication.translate
        TraitView.setWindowTitle(_translate("TraitView", "Form"))
        self.btn_edit_trait.setText(_translate("TraitView", "Edit"))
        self.btn_delete_trait.setText(_translate("TraitView", "Delete"))
